plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'kr.windy.mariwoo'
    compileSdk 35

    defaultConfig {
        applicationId "kr.windy.mariwoo"
        minSdk 30
        targetSdk 35
        versionCode 2
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }

}
dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.legacy.support.v4
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation 'com.google.android.material:material:1.12.0'
    //통신
    implementation 'com.squareup.okhttp3:okhttp:4.9.0';
    // 이미지 그리기
    implementation 'com.github.bumptech.glide:glide:4.13.0'
    
    implementation 'androidx.core:core-splashscreen:1.0.0-rc01'
    // 전화번호 포맷 통일 라이브러리
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.2.0'

    // 캘린더뷰
    implementation 'com.github.prolificinteractive:material-calendarview:2.0.1'
    implementation 'com.jakewharton.threetenabp:threetenabp:1.1.1'


    // 네이버 로그인
    implementation 'com.navercorp.nid:oauth:5.9.1' // jdk 11

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.legacy:legacy-support-core-utils:1.0.0'
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.fragment:fragment-ktx:1.7.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.moshi:moshi-kotlin:1.11.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.2'
    implementation 'com.airbnb.android:lottie:3.1.0'
}